In [1]:
import numpy as np
import torch

In [5]:
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)
D = np.random.randn(3,7)

# remember that this is different thing than matrix multiplication, it's just a multiplying the elements of the same index
print(np.round(C*D, 2), '\n\n')

print(np.round(A@B, 2), '\n\n')
print(np.round(np.matmul(A,B), 2), '\n\n') # the same as A@B
print(np.round(C.T@A, 2), '\n\n')
# print(np.round(B@C, 2), '\n\n')

[[ 2.06  0.92  0.01  0.37  0.02 -0.02  0.85]
 [-0.55  1.23  2.4   0.02 -0.99 -0.05 -0.01]
 [-0.02  1.73 -0.57 -0.89  0.61 -0.6   0.05]] 


[[-0.35 -0.2   4.66 -0.51 -0.55]
 [-0.55  1.78 -1.52  0.13 -0.22]
 [ 1.67 -1.85 -1.51  0.61 -1.95]] 


[[-0.35 -0.2   4.66 -0.51 -0.55]
 [-0.55  1.78 -1.52  0.13 -0.22]
 [ 1.67 -1.85 -1.51  0.61 -1.95]] 


[[-0.31 -0.87  3.19  3.23]
 [-0.91 -0.04 -2.49  2.94]
 [-2.19  1.01  0.38 -0.59]
 [ 0.01  0.08  1.58 -1.03]
 [-0.28  1.25  0.71 -5.46]
 [ 0.   -0.57 -0.1   2.63]
 [ 0.05  0.5  -0.55 -2.14]] 




## __Pytorch__

In [7]:
A = torch.randn(3,4)
B = torch.randn(4,5)
C1 = np.random.randn(4, 7)
C2 = torch.tensor(C1, dtype=torch.float)

# some multiplications
print(np.round(A@B, 1), '\n\n')
print(np.round(A@C1, 1), '\n\n')
print(np.round(A@C2, 1), '\n\n')

tensor([[-0.6000,  1.6000,  1.8000, -1.6000, -0.0000],
        [-1.2000,  4.1000,  5.5000, -4.8000, -0.1000],
        [ 0.6000,  0.9000,  6.9000, -0.3000,  0.2000]]) 


tensor([[ 1.9000,  0.4000, -0.5000,  0.3000, -0.1000,  0.0000,  0.6000],
        [ 5.6000,  1.1000, -1.9000,  0.8000, -1.6000, -0.5000,  1.0000],
        [ 1.7000,  0.5000, -4.8000,  0.4000, -3.5000,  2.0000, -2.6000]],
       dtype=torch.float64) 


tensor([[ 1.9000,  0.4000, -0.5000,  0.3000, -0.1000,  0.0000,  0.6000],
        [ 5.6000,  1.1000, -1.9000,  0.8000, -1.6000, -0.5000,  1.0000],
        [ 1.7000,  0.5000, -4.8000,  0.4000, -3.5000,  2.0000, -2.6000]]) 


