In [1]:
import numpy as np
import torch

In [10]:
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)
D = np.random.randn(3,7)

# remember that this is different thing than matrix multiplication, it's just a multiplying the elements of the same index
print(np.round(C*D, 2), '\n\n')

print(np.round(A@B, 2), '\n\n')
print(np.round(np.matmul(A,B), 2), '\n\n') # the same as A@B
print(np.round(C.T@A, 2), '\n\n')
# print(np.round(B@C, 2), '\n\n')

[[-0.31  0.09  0.79 -0.71  0.11 -0.03 -0.05]
 [ 0.33 -0.29 -1.83 -0.37 -0.48  0.9   0.14]
 [ 0.62  0.01 -0.43  0.7   0.04  1.53  0.32]] 


[[-2.51  0.94 -2.45  0.05  0.73]
 [-1.52  0.04  1.45  2.36 -0.42]
 [ 1.18 -2.25 -5.91 -7.98  1.2 ]] 


[[-2.51  0.94 -2.45  0.05  0.73]
 [-1.52  0.04  1.45  2.36 -0.42]
 [ 1.18 -2.25 -5.91 -7.98  1.2 ]] 


[[-3.73 -0.06 -2.59  4.18]
 [-0.33 -0.97  0.39  0.68]
 [-0.48  1.72 -1.56 -0.  ]
 [-1.01 -2.49 -5.95  2.92]
 [-0.44 -0.31 -1.56  0.8 ]
 [-3.57 -1.46 -3.96  4.79]
 [ 1.43  0.22  1.97 -1.82]] 




## __Pytorch__

In [15]:
A = torch.randn(3,4)
B = torch.randn(4,5)
C1 = np.random.randn(4, 7)
C2 = torch.tensor(C1, dtype=torch.float)

# some multiplications
print(np.round(A@B, 1), '\n\n')
print(np.round(A@C1, 1), '\n\n')
print(np.round(A@C2, 1), '\n\n')

tensor([[-3.1000,  1.1000,  1.0000,  0.9000,  3.4000],
        [ 0.4000, -0.5000, -0.9000,  0.2000,  0.3000],
        [ 0.1000, -1.4000, -1.1000, -1.6000, -0.0000]]) 


tensor([[-3.9000, -0.9000, -3.4000, -1.8000,  0.8000, -4.2000, -2.4000],
        [ 1.7000, -0.2000,  1.1000,  0.7000, -1.9000, -0.6000,  1.4000],
        [-0.2000,  2.8000,  2.7000,  0.0000,  3.1000,  1.5000, -2.9000]],
       dtype=torch.float64) 


tensor([[-3.9000, -0.9000, -3.4000, -1.8000,  0.8000, -4.2000, -2.4000],
        [ 1.7000, -0.2000,  1.1000,  0.7000, -1.9000, -0.6000,  1.4000],
        [-0.2000,  2.8000,  2.7000,  0.0000,  3.1000,  1.5000, -2.9000]]) 


