In [1]:
import numpy as np
import torch
import torch.nn as nn

In [2]:
M = np.array([
    [-5, 1, 10],
    [2, 8, 5]
])

global_min = np.min(M)
print(global_min)

min_in_cols = np.min(M, axis = 0)
print(min_in_cols)

min_in_rows = np.min(M, axis = 1)
print(min_in_rows)

-5
[-5  1  5]
[-5  2]


In [3]:
min_in_cols_t = torch.min(torch.Tensor(M), axis=0)

print(min_in_cols_t.values)
print(min_in_cols_t.indices)

tensor([-5.,  1.,  5.])
tensor([0, 0, 1])
