In [1]:
import numpy as np
import torch

In [6]:
# Always different
np.random.randn(5)

array([-1.0383734 ,  1.24814841, -0.34020615,  1.09945735, -0.57455806])

In [11]:
# We'll get always the same results
np.random.seed(17)

print(np.random.randn(5))
print(np.random.randn(5))

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]


In [35]:
# Newer way to apply random seed via random state, more flexible, local scope for the seed
# Certain variables follow the seed, and others - not

random_seed_1 = np.random.RandomState(17)
random_seed_2 = np.random.RandomState(20210530)

print(random_seed_1.randn(5))
print(random_seed_2.randn(5))
print(random_seed_1.randn(5))
print(random_seed_2.randn(5))
print(np.random.randn(5))

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[-0.24972681 -1.01951826  2.23461339  0.72764703  1.2921122 ]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]
[ 1.15494929 -0.0015467  -0.11196868 -1.08136725  0.10265891]
[ 0.03260213  2.52525474 -0.17490347 -0.84195834  0.07660079]


In [36]:
torch.randn(5)

tensor([ 0.5230, -0.5249,  1.3124,  0.8785,  0.1664])

In [48]:
torch.manual_seed(17)
print(torch.randn(5))

print(np.random.randn(5)) # not affected by torch random seed

tensor([-1.4135,  0.2336,  0.0340,  0.3499, -0.0145])
[-1.89479101 -0.24863524  1.2949701  -1.2771433  -1.23068842]
