In [15]:
import numpy as np
import torch

In [12]:
# creating a matrix
np_matrix = np.array([
    [1,2,3,4],
    [5,6,7,8]
    ])

# printing the original matrix
print(np_matrix, '\n\n')

# transposing, trans-trans matrix
print(np_matrix.T, '\n\n')
print(np_matrix.T.T, '\n\n')

[[1 2 3 4]
 [5 6 7 8]] 


[[1 5]
 [2 6]
 [3 7]
 [4 8]] 


[[1 2 3 4]
 [5 6 7 8]] 




### __Pytorch__

In [20]:
pt_vector = torch.tensor(
    [1,2,3,4]
    )

# printing the original matrix
print(pt_vector, '\n\n')

# transposing, trans-trans matrix
print(pt_vector.T, '\n\n')
print(pt_vector.T.T, '\n\n')

tensor([1, 2, 3, 4]) 


tensor([1, 2, 3, 4]) 


tensor([1, 2, 3, 4]) 




In [17]:
# creating a matrix
pt_matrix = torch.tensor([
    [1,2,3,4],
    [5,6,7,8]
    ])

# printing the original matrix
print(pt_matrix, '\n\n')

# transposing, trans-trans matrix
print(pt_matrix.T, '\n\n')
print(pt_matrix.T.T, '\n\n')

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]]) 


tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]]) 


tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]]) 


